services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/develop/backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:genesis@mongo:27017

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/develop/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./data/dump:/data/dump
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: genesis
