services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/develop/backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:genesis@mongo:27017

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/develop/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgdb:/var/lib/postgresql/data
      - ./data/dump/psotgres:/data/dump
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: genesis
      POSTGRES_DB: genesisdb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "genesisdb"]
      interval: 1s
      timeout: 5s
      retries: 10
